[02:54:45] [Server thread/ERROR]: "Silently" catching entity tracking error.
net.minecraft.util.ReportedException: Adding entity to track
	at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:230) [mn.class:?]
	at cpw.mods.fml.common.registry.EntityRegistry.tryTrackingEntity(EntityRegistry.java:364) [EntityRegistry.class:?]
	at net.minecraft.entity.EntityTracker.func_72786_a(EntityTracker.java:61) [mn.class:?]
	at net.minecraft.world.WorldManager.func_72703_a(SourceFile:31) [mp.class:?]
	at net.minecraft.world.World.func_72923_a(World.java:1347) [ahb.class:?]
	at net.minecraft.world.WorldServer.func_72923_a(WorldServer.java:844) [mt.class:?]
	at net.minecraft.world.World.func_72868_a(World.java:3304) [ahb.class:?]
	at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:921) [apx.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:46) [ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12) [ChunkIOProvider.class:?]
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344) [AsynchronousExecutor.class:?]
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302) [AsynchronousExecutor.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12) [ChunkIOExecutor.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
	at net.minecraft.world.World.func_147439_a(World.java:345) [ahb.class:?]
	at net.minecraft.world.Teleporter.func_77184_b(SourceFile:85) [ahp.class:?]
	at net.minecraft.world.Teleporter.func_77185_a(SourceFile:50) [ahp.class:?]
	at net.minecraft.server.management.ServerConfigurationManager.transferEntityToWorld(ServerConfigurationManager.java:597) [oi.class:?]
	at net.minecraft.server.management.ServerConfigurationManager.func_82448_a(ServerConfigurationManager.java:522) [oi.class:?]
	at net.minecraft.entity.Entity.func_71027_c(Entity.java:2055) [sa.class:?]
	at net.minecraft.entity.Entity.func_70030_z(Entity.java:363) [sa.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:193) [sv.class:?]
	at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:157) [sw.class:?]
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:318) [sa.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1561) [sv.class:?]
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206) [sw.class:?]
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:30) [yg.class:?]
	at net.minecraft.entity.monster.EntityZombie.func_70071_h_(EntityZombie.java:303) [yq.class:?]
	at net.minecraft.entity.monster.EntityPigZombie.func_70071_h_(SourceFile:63) [yh.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:2070) [ahb.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648) [mt.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:2034) [ahb.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1887) [ahb.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.IllegalStateException: Entity is already tracked!
	at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:196) ~[mn.class:?]
	... 41 more
